# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_Qpt4ShG02h5YytJLsadjpeBFyuFIRH
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/API_SP.POP.TOTL_DS2_en_csv_v2_34.csv', skiprows=3)
metadata_country = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_34.csv')
metadata_indicator = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/Metadata_Indicator_API_SP.POP.TOTL_DS2_en_csv_v2_34.csv')

df.info()

metadata_country.info()

metadata_indicator.info()

df = df.drop(columns=['Unnamed: 69'])
metadata_country = metadata_country.drop(columns=['Unnamed: 5'])
metadata_indicator = metadata_indicator.drop(columns=['Unnamed: 4'])

df.head()

metadata_country.head()

metadata_indicator.sample()

# Make rules that keep only country-level entities (exclude aggregates (in this case the aggregates is NaN) using metadata)
valid_countries = metadata_country.loc[metadata_country['Region'].notna()]['Country Code']

df_country= df[df['Country Code'].isin(valid_countries)] # Filtered country with the "valid_countries" as a rules
df_2024 = df_country[['Country Name', '2024']].dropna()

top10 = (df_2024.sort_values(by='2024', ascending=False).head(10))

"""We use the "metadata_country" to; filtered between country data and region data, and skipped the noise"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.bar(top10['Country Name'], top10['2024'])
plt.xticks(rotation=45, ha='right')
plt.title('Top 10 Countries by Population (2024)')
plt.ylabel('Population')
plt.xlabel('Country')
plt.tight_layout()
plt.show()

top_country = ['India', 'China', 'United States']
years = ['2020', '2021', '2022', '2023', '2024'] # Range of Time

trend = (df_country[
    df_country['Country Name'].isin(top_country)]
         [['Country Name'] + years])

df_long = trend.melt(
    id_vars='Country Name',
    value_vars=years,
    var_name='Year'
    )