# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_Qpt4ShG02h5YytJLsadjpeBFyuFIRH
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/API_SP.POP.TOTL_DS2_en_csv_v2_34.csv', skiprows=3)
metadata_country = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_34.csv')
metadata_indicator = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/Metadata_Indicator_API_SP.POP.TOTL_DS2_en_csv_v2_34.csv')

df.info()

metadata_country.info()

metadata_indicator.info()

# Delete parcing row
df = df.drop(columns=['Unnamed: 69'])
metadata_country = metadata_country.drop(columns=['Unnamed: 5'])
metadata_indicator = metadata_indicator.drop(columns=['Unnamed: 4'])

df.head()

"""Although aggregate entities are not explicitly labeled in the main dataset, the World Bank provides entity definitions in the country metadata. By filtering out records where the region is marked as “Aggregates,” we ensure that only valid country-level observations are included in the analysis."""

metadata_country.head()

"""From Metadata_Country file we know that country-level entities can be identified by having both Region and IncomeGroup populated, while aggregate entities exhibit missing values in one or both of these columns."""

# make sure the rules before use it for filtering country
metadata_country[['Region', 'IncomeGroup']].isna().value_counts()

"""Based on the output, 215 entities have both Region and IncomeGroup defined, indicating country-level records. Additionally, 48 entities have both fields missing, which corresponds to aggregate entities. There are also 2 entities where Region is defined but IncomeGroup is missing, representing regional aggregates rather than countries."""

metadata_indicator.sample()

"""## **1. Which Countries have the largest populations in the most recent year, and how large is the population gap compared to other countries?**"""

# Make rules that keep only country-level entities (exclude aggregates (in this case the aggregates is NaN) using metadata)
valid_countries = metadata_country.loc[
    metadata_country['Region'].notna()
    & metadata_country['IncomeGroup'].notna()
    ]['Country Code']

df_country= df[df['Country Code'].isin(valid_countries)] # Filtered country with the "valid_countries" as a rules
df_2024 = df_country[['Country Name', '2024']].dropna()

top10 = (df_2024.sort_values(by='2024', ascending=False).head(10))

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.bar(top10['Country Name'], top10['2024'])
plt.xticks(rotation=45, ha='right')
plt.title('Top 10 Countries by Population (2024)')
plt.ylabel('Population')
plt.xlabel('Country')
plt.tight_layout()
plt.show()

"""The three countries with the largest populations are India, China, and the United States. To provide context for this snapshot, the population levels of these countries are compared across the 2020–2024 period to observe short-term changes

## **2. What is the income group composition of the most countries, and do highly populated countries tend to fail into specific income groups?**
"""

import matplotlib.pyplot as plt

top_country = ['United States', 'China', 'India']
df_top = (
    metadata_country[
        metadata_country['TableName'].isin(top_country)
    ][['TableName', 'IncomeGroup']]
)

income_order = {
    'Low income': 1,
    'Lower middle income': 2,
    'Upper middle income': 3,
    'High income': 4
}

df_top['IncomeCode'] = df_top['IncomeGroup'].map(income_order)

# plot
plt.figure(figsize=(7,5))
plt.bar(df_top['TableName'], df_top['IncomeCode'])

plt.yticks(
    list(income_order.values()),
    list(income_order.keys())
)

plt.xlabel('Country')
plt.ylabel('Income Group')
plt.title('Income Group Classification of Top Countries')
plt.tight_layout()
plt.show()

"""Although the United States, China, and India are all globally influential countries, they belong to different income groups. This highlights that global influence and economic scale do not necessarily translate into high per-capita income, underscoring the importance of income-group stratification in cross-country analyses.

## **3. How has the population of the three most populous countries grown over the past four years, and do their growth trends exhibit different petterns?**
"""

import numpy as np

top_country = ['United States', 'China', 'India']
years = ['2020', '2021', '2022', '2023', '2024'] # Range of Time

population_subset = (df_country[
    df_country['Country Name'].isin(top_country)]
         [['Country Name', 'Country Code'] + years])

x = np.arange(len(years))
width = 0.25

plt.figure(figsize=(10,6))

for i, country in enumerate(top_country):
  values = population_subset[population_subset['Country Name'] == country][years].values.flatten()

# Plot
  plt.bar(
      x+i * width,
      values,
      width,
      label=country
  )

plt.xticks(x + width, years)
plt.xlabel('Year')
plt.ylabel('Population')
plt.title("Top 3 Country with Largest Population (2020-2024)")
plt.legend()
plt.tight_layout()
plt.show()

"""From 2020 to 2024, India experiences steady population growth, China remains largely stable, and the United States shows moderate increases. This comparison reflects short-term population dynamics rather than long-term trends.

## **4. What is the composition of the number of countries in each income group, and does this classification change over the 2020–2024 period?**
"""

print(metadata_country['IncomeGroup'].unique())

df_base = (
    df_country[df_country['Country Code'].str.len() == 3]
    .merge(
        metadata_country[['Country Code', 'IncomeGroup']],
        on='Country Code',
        how='left'
    )
)

df_base = df_base.dropna(subset=['IncomeGroup'])

# Calculate the number of countries per income group per year
records = []
for year in years:
    counts = (
        df_base[['Country Code', 'IncomeGroup']]
        .drop_duplicates()
        .groupby('IncomeGroup')
        .size()
    )
    counts.name = year
    records.append(counts)

df_bar = pd.concat(records, axis=1).fillna(0)

# plot
plt.figure(figsize=(10,6))
df_bar.T.plot(kind='bar')

plt.xlabel('Year')
plt.ylabel('Number of Countries')
plt.title('Number of Countries by Income Group (2020–2024)')
plt.xticks(rotation=0)
plt.legend(title='Income Group')
plt.tight_layout()
plt.show()

"""The number of countries in each income group from 2020 to 2024. The counts remain constant across years, reflecting that income group classifications are treated as static metadata in this dataset rather than time-varying economic indicators. This stability provides a structural baseline for subsequent analyses comparing population and economic variables across income groups"""

df_hist = (
    df_country[
        df_country['Country Code'].str.len() == 3][['Country Code', '2024']]
        .dropna().merge(
        metadata_country[['Country Code', 'IncomeGroup']],
        on='Country Code',
        how='left'
    )
)

df_hist['2024'] = pd.to_numeric(df_hist['2024'], errors='coerce')
df_hist = df_hist.dropna(subset=['IncomeGroup', '2024'])

df_hist['IncomeGroup'].value_counts()

"""## **5. Over the past 10 years, do HighIncome countries exhibit a homogeneous population distribution, or is there substantial variation within the group?**"""

years_10 = [
    '2015','2016','2017','2018','2019',
    '2020','2021','2022','2023','2024'
]

df_hist = (
    df_country[
        df_country['Country Code'].str.len() == 3
    ][['Country Code'] + years_10]
    .merge(
        metadata_country[['Country Code', 'IncomeGroup']],
        on='Country Code',
        how='left'
    )
)

df_hist = df_hist[df_hist['IncomeGroup'] == 'High income']

df_long = df_hist.melt(
    id_vars=['Country Code', 'IncomeGroup'],
    value_vars=years_10,
    var_name='Year',
    value_name='Population'
)

df_long['Population'] = pd.to_numeric(df_long['Population'], errors='coerce')
df_long = df_long.dropna(subset=['Population'])

df_long['log_pop'] = np.log10(df_long['Population'])

# Plot
plt.figure(figsize=(10,6))
bins = np.linspace(
    df_long['log_pop'].min(),
    df_long['log_pop'].max(),
    30
)

plt.hist(
    df_long['log_pop'],
    bins=bins,
    alpha=0.5,
    edgecolor='black',
    linewidth=0.8
)

plt.xlabel('Population (log10 scale)')
plt.ylabel('Number of observations')
plt.title('Population Distribution of High-Income Countries (Last 10 Years)')
plt.tight_layout()
plt.show()

"""Because high-income countries exhibit a wide and heterogeneous population distribution over the last decade, subsequent analyses should avoid treating them as a single homogeneous group. Population-aware stratification or per-capita normalization is therefore required to ensure valid cross-country comparisons"""

