# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_Qpt4ShG02h5YytJLsadjpeBFyuFIRH
"""

import pandas as pd

# Skip rows that contain metadata
df1 = pd.read_csv('/content/drive/MyDrive/Dataset/World Bank/API_SP.POP.TOTL_DS2_en_csv_v2_34.csv', skiprows=3)

df1.info()

# Remove empty columns cause it's a parsing artifact
df1 = df1.drop(columns=['Unnamed: 69'])

df1.head()

df1.describe()

print(df1.isnull().sum())

# # We want to identify the countries with the largest populations over the last four years
# cols = ['Country Name', '2021', '2022', '2023', '2024']
# df_recent = df1[cols]

# df_2024 = df_recent[['Country Name', '2024']].dropna() # The last year
# top_10 = df_2024.sort_values(by='2024', ascending=False).head(10) # Top 10 country with largest populations

country = df1[df1['Country Code'].str.len() == 3] # Filter country-level records based on ISO country codes

df_2024 = (
    country[['Country Name', '2024']]
)
top10 = (
    country[['Country Name', '2024']].dropna()
    .sort_values(by='2024', ascending=False).head(10) # Top 10 Country with largest population
)

import matplotlib as plt

top_10.plot(
    x=top10,
    y='2024',
    kind='bar',
    title='Top 10 Countries by Population (2024)'
)

